'Use this file to enhance and extend the component generated by the DAQ Assistant.
'
'Refer to "Adding Custom Functionality to a .NET DAQ Component" in the NI Measurement Studio Help for more
'information.
'
'This file is never regenerated by the DAQ Assistant, so any changes you make here will not be overwritten
'if you modify your DAQmx task with the DAQ Assistant configuration editor.

Imports System
Imports NationalInstruments
Imports NationalInstruments.DAQmx
Imports NationalInstruments.DAQmx.ComponentModel

'This partial class extends the class defined by the DAQ Assistant in DaqTask1.vb
Public Partial Class DaqTask1Component
    ''' <summary>
    ''' Initializes a new instance of the component.
    ''' </summary>
    Protected Overrides Sub Initialize()
        MyBase.Initialize()

        'TODO: Perform custom initialization here.
        '      This method is called when the component is created.
    End Sub

    ''' <summary>
    ''' Clean up any resources being used.
    ''' </summary>
    ''' <param name="disposing">True if managed resources need to be disposed; otherwise, False.</param>
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        'TODO: Perform custom clean-up here.
        '      
        '      Refer to "Implementing a Dispose Method" in the .NET Framework documentation for more
        '      information on the Disposable Pattern.

        If disposing Then
        End If

        MyBase.Dispose(disposing)
    End Sub

    ''' <summary>
    ''' Raises the TaskCreated event.
    ''' </summary>
    ''' <param name="e">The event argument of the TaskCreated event.</param>
    Protected Overrides Sub OnTaskCreated(ByVal e As EventArgs)
        'TODO: Perform custom DAQmx task configuration, such as advanced timing and triggering, here.
        '      
        '      Refer to "Adding Custom Functionality to a .NET DAQ Component" in the NI Measurement
        '      Studio Help for an example of advanced DAQmx task configuration.

        MyBase.OnTaskCreated(e)
    End Sub
End Class
